# Generated by Django 2.0.1 on 2018-01-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Bool',
        ),
    ]
