# Generated by Django 2.0.1 on 2018-01-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180129_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bool',
        ),
    ]
