# Generated by Django 2.0.1 on 2018-01-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180129_1417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'price')},
        ),
    ]
