# Generated by Django 2.0.1 on 2018-01-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180130_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=64, verbose_name='书名'),
        ),
    ]
